name: Update YML on PR Merge

on:
  push:
    # branches:
    #   - main
  pull_request:
    # types: [opened]

jobs:
  update-yml:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    # Checkout o repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configura o Git para commits
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin ${{ github.base_ref }}
        git checkout ${{ github.base_ref }}

    # Extrair informações da PR
    - name: Extract PR Information
      id: extract_pr_info
      run: |
        echo "title=$(echo '${{ github.event.pull_request.title }}')" >> $GITHUB_ENV
        echo "number=$(echo '${{ github.event.pull_request.number }}')" >> $GITHUB_ENV
        echo "sha=$(echo '${{ github.sha }}')" >> $GITHUB_ENV

    - name: see file metadata
      run: |
        ls -la
        cat metadata.yaml


    # Atualizar o arquivo YML
    - name: Update YML file
      run: |
        new_version="\  - sha: ${{ env.sha }}\n    changeNotes: \"PR #${{ env.number }}: ${{ env.title }}\""
        sed -i "/^versions:/a$new_version" metadata.yaml

    - name: see file metadata
      run: cat metadata.yaml


    # Fazer commit e push das mudanças
    - name: Commit and push changes
      run: |
        git add metadata.yaml
        git commit -m "Add version entry for PR #${{ env.number }}: ${{ env.title }}"
        git push origin ${{ github.ref_name }}
